# CAVEAT - THIS FILE MUST BE USED FOR LOCAL DEVELOPMENT PURPOSE ONLY
# For full spec of docker-compose: @see @see https://docs.docker.com/compose/compose-file/
version: '3'

services:

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    volumes:
      - $HOME/mysql_data:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: mysql -e 'SELECT 1' || exit 1
      interval: 60s

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "local-example-output:1:1"
    ports:
      - 9092:9092

  laravel:
    image: bitnami/php-fpm:7.3-prod
    container_name: laravel
    volumes:
      - ..:/app
      - ./custom-php.ini:/opt/bitnami/php/etc/conf.d/custom-php.ini
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=local_example
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    healthcheck:
      test: /opt/bitnami/php/bin/php /app/artisan || exit 1
      interval: 60s

  nginx:
    image: bitnami/nginx:latest
    container_name: nginx
    ports:
      - 8000:8000
    volumes:
      - ..:/app
      - ./laravel.conf:/opt/bitnami/nginx/conf/server_blocks/laravel.conf
    depends_on:
      - laravel
    healthcheck:
      test: curl -s http://localhost:8000 || exit 1
      interval: 60s
